import { ReactNode } from "react";
import { NextIntlClientProvider } from "next-intl";

import "@/app/[locale]/(public)/globals.css";
import { SocialMediaBar, Navbar, Footer } from "@/features/landing/";

export const metadata = {
  title: "wozniak.website",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: ReactNode;
  argPublic: string;
  params: { locale: string };
};

const RootLayout: React.FC<RootLayoutProps> = ({
  children,
  params: { locale },
}) => {
  const messages = require(`@/messages/${locale}.json`);

  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <html lang={locale}>
        <body className="box-border flex flex-col items-center overflow-x-hidden max-w-screen">
          <SocialMediaBar />
          <Navbar />
          <div className="box-border flex flex-col flex-grow">{children}</div>
          <Footer />
        </body>
      </html>
    </NextIntlClientProvider>
  );
};
export default RootLayout;
